name: Run unit tests

on: 
  push:
    branches:
      - dev

permissions:
  id-token: write   # Required for OIDC
  contents: write # Required for pushing to UAT branch

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-region: us-east-2
          role-to-assume: ${{ secrets.CI_CD_ROLE_ARN }}
    
      - name: Setup Go
        uses: actions/setup-go@v6
        with:
            go-version: '1.26'
    
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: 1.14.5

      
      - name: Install Terragrunt
        uses: gruntwork-io/terragrunt-action@v3
        with:
            tg_version: '0.99.4'
            tofu_version: '1.11.5'

      - name: Run Terratest
        run: |
          cd test/unit/        
          go mod tidy
          go test -short

  promote-to-uat:
    needs: run-unit-tests
    runs-on: ubuntu-latest
    environment: uat

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Merge dev into UAT
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git switch uat
          git merge origin/dev --no-ff -m "Promote dev to UAT"
          git push origin uat